env: dev
domain: dev.example.jp
zones:
  osk:
    server_ids_in_zone:
      - sv01
      - sv02
  tky:
    server_ids_in_zone:
      - sv01
      - sv02
param1:
  sv01-osk: 10
  sv02-osk: 20
  sv01-tky: 20
  sv02-tky: 10
