env: production
domain: example.jp
zones:
  osk:
    server_ids_in_zone:
      - sv01
      - sv02
      - sv03
  tky:
    server_ids_in_zone:
      - sv01
      - sv02
      - sv03
param1:
  sv01-osk: 20
  sv02-osk: 30
  sv03-osk: 10
  sv01-tky: 10
  sv02-tky: 20
  sv03-tky: 30
